### ISSUE TITLE
User Story: View post list

### ISSUE THREAD

**Issue by carl2087** [carl2087/the-final-whistle#23]
As a **user** I can **View a list of posts** so that **I can select one to read**

### Acceptance Criteria:

* List of posts show up on home screen for user
* User is able to see a snippet of text with an image on each post
* User can click the post to see it in it's entirety with any comments that have been left

### Tasks:

- [ ] Set up models to handle the data
- [ ] Set up the HTML pages to show the data
- [ ] Set up CRUD functionality
- [ ] Test Functionality
