### ISSUE TITLE
As a user I can click a button to share my posts to my social accounts so that I can easily share my views elsewhere

### ISSUE THREAD

**Issue by carl2087** [carl2087/the-final-whistle#35]
As a **user** I can **click a button to share my posts to my social accounts** so that **so that I can easily share my views elsewhere**

### Acceptance Criteria:

* Social account buttons appear under posts
* When clicked shares the post on the relevant site

### Tasks:

- [ ] Set up logic in models views and URL paths
- [ ] buttons appear under posts
- [ ] when clicked share the posts automatically
