### ISSUE TITLE
User Story:

### ISSUE THREAD

**Issue by carl2087** [carl2087/the-final-whistle#38]
Post detail view was not rendering when link clicked on

### Debugging steps

* Checked all code written for view so far
* Searched through Django Documentation
* Searched through google and Stack overflow
* Found and corrected spelling mistake in code

### Tasks:

- [ ] Wrote basic template code to check if view was rendering correctly 
- [ ] pushed correct view code to GItHub repo
- [ ] Updated template code 
- [ ] Pushed rest of code to GitHUb
